name: Docker Image CI

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
    
env:
  IMAGE_NAME: hello-world

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v3
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Extract metadata for Docker
      uses: docker/metadata-action@v3
      id: meta
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
        
    - name: Build source for linux/amd64
      uses: addnab/docker-run-action@v3
      with:
        registry: docker.io
        image: fjzhangzzz/alpine-gcc:main
        options: -v ${{ github.workspace }}:/work -e BUILD_TYPE=Release --platform=linux/amd64
        run: |
          ls -l /work && uname -a
          [[ -d /work/build ]] && rm -rf /work/build/* || mkdir -p /work/build
          cd /work/build
          cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
          make && file hello-world

    - name: Build image for linux/amd64
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        platforms: linux/amd64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        
    - name: Build source for linux/arm64
      uses: addnab/docker-run-action@v3
      with:
        registry: docker.io
        image: fjzhangzzz/alpine-gcc:main
        options: -v ${{ github.workspace }}:/work -e BUILD_TYPE=Release --platform=linux/arm64
        run: |
          ls -l /work && uname -a
          [[ -d /work/build ]] && rm -rf /work/build/* || mkdir -p /work/build
          cd /work/build
          cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
          make && file hello-world

    - name: Build image for linux/arm64
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        platforms: linux/arm64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Push to Docker Hub
      run: docker push -a ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
      
