name: Publish Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
      - 'v*'
  pull_request:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  IMAGE_NAME: hello-world

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build source for linux/amd64
        uses: addnab/docker-run-action@v3
        with:
          registry: docker.io
          image: fjzhangzzz/alpine-gcc:main
          options: -v ${{ github.workspace }}:/work -e BUILD_TYPE=Release --platform=linux/amd64
          run: |
            DISTRDIR=/work/dist
            BUILDDIR=/work/build
            [[ -d ${DISTRDIR} ]] && ls -l ${DISTRDIR} || mkdir -p ${DISTRDIR}
            echo "list distr" && ls -lR ${DISTRDIR}
            [[ -d ${BUILDDIR} ]] && rm -rf ${BUILDDIR}/* || mkdir -p ${BUILDDIR}
            cd ${BUILDDIR} && cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} .. && make && cp hello-world ${DISTRDIR}/hello-world_linux_amd64
      - name: Build source for linux/arm64
        uses: addnab/docker-run-action@v3
        with:
          registry: docker.io
          image: fjzhangzzz/alpine-gcc:main
          options: -v ${{ github.workspace }}:/work -e BUILD_TYPE=Release --platform=linux/arm64
          run: |
            DISTRDIR=/work/dist
            BUILDDIR=/work/build
            [[ -d ${DISTRDIR} ]] && ls -l ${DISTRDIR} || mkdir -p ${DISTRDIR}
            echo "list distr" && ls -lR ${DISTRDIR}
            [[ -d ${BUILDDIR} ]] && rm -rf ${BUILDDIR}/* || mkdir -p ${BUILDDIR}
            cd ${BUILDDIR} && cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} .. && make && cp hello-world ${DISTRDIR}/hello-world_linux_arm64
        
      - name: Display
        run: echo "list ${{ github.workspace }}" && ls -lR ${{ github.workspace }}
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: hello-world
          path: ${{ github.workspace }}/dist/
        
  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@master
    
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: hello-world
        path: ${{ github.workspace }}/dist/
